---
# Common variables for all hosts

# MariaDB/MySQL credentials
# OpenExchange configuration
ox_admin_username: "oxadmin"
ox_name: "openexchange-cluster"
ox_configdb_name: "configdb"
configdb_user: "configdb_user"
ox_master_username: "oxmaster"

# UI specific variables
openexchange_ui_domain: "ui.yourdomain.com"
openexchange_ui_cert_name: "ui.yourdomain.com" # Should match the domain for Certbot

# IP addresses for OpenExchange VMs (these should match your terraform.tfvars)
openexchange_backend_ip: "138.231.110.251"
openexchange_ui_ip: "138.231.110.252"
openexchange_services_ip: "138.231.110.253"

# SSH User for VM access (this should match your terraform.tfvars)
vm_ssh_user: "ubuntu"

# Domain specific variables
tech_domain:
  name: "ens-paris-saclay.fr" # Used for mail server configurations

# Environment and feature flags
env_type: "dev" # or 'prod'
features:
  use_custom_login: false # Set to true if you have a custom login page
  use_custom_sshd_config: false # Set to true if you want to use a custom sshd_config
# dimail_login_version: "1.0" # Only needed if use_custom_login is true

# OpenExchange parameters (e.g., for OIDC integration)
ox_params: [] # e.g., ['oidc'] if OIDC is used

# Postfix TLS certificate paths
postfix_tls_cert_file: "/etc/ssl/certs/postfix.pem" # Placeholder, update with actual path
postfix_tls_key_file: "/etc/ssl/private/postfix.key" # Placeholder, update with actual path
